//! Physical keys, from the names browsers give them to USB HID usages.
//!
//! A `KeyboardEvent.code` names the key's position — "KeyQ" is the key left
//! of W on any layout — which is exactly what the protocol sends: the agent
//! applies its own layout, so AltGr and dead keys behave as on a keyboard
//! plugged into the device. The names are the W3C UI Events KeyboardEvent
//! code values; the native viewer's table, keyed by winit's names for the
//! same list, gives the same usages.

/// The USB HID keyboard usage (page 0x07) of the key a browser calls `code`.
pub fn hid_usage(code: &str) -> Option<u16> {
    Some(match code {
        "KeyA" => 0x04,
        "KeyB" => 0x05,
        "KeyC" => 0x06,
        "KeyD" => 0x07,
        "KeyE" => 0x08,
        "KeyF" => 0x09,
        "KeyG" => 0x0A,
        "KeyH" => 0x0B,
        "KeyI" => 0x0C,
        "KeyJ" => 0x0D,
        "KeyK" => 0x0E,
        "KeyL" => 0x0F,
        "KeyM" => 0x10,
        "KeyN" => 0x11,
        "KeyO" => 0x12,
        "KeyP" => 0x13,
        "KeyQ" => 0x14,
        "KeyR" => 0x15,
        "KeyS" => 0x16,
        "KeyT" => 0x17,
        "KeyU" => 0x18,
        "KeyV" => 0x19,
        "KeyW" => 0x1A,
        "KeyX" => 0x1B,
        "KeyY" => 0x1C,
        "KeyZ" => 0x1D,
        "Digit1" => 0x1E,
        "Digit2" => 0x1F,
        "Digit3" => 0x20,
        "Digit4" => 0x21,
        "Digit5" => 0x22,
        "Digit6" => 0x23,
        "Digit7" => 0x24,
        "Digit8" => 0x25,
        "Digit9" => 0x26,
        "Digit0" => 0x27,
        "Enter" => 0x28,
        "Escape" => 0x29,
        "Backspace" => 0x2A,
        "Tab" => 0x2B,
        "Space" => 0x2C,
        "Minus" => 0x2D,
        "Equal" => 0x2E,
        "BracketLeft" => 0x2F,
        "BracketRight" => 0x30,
        "Backslash" => 0x31,
        "Semicolon" => 0x33,
        "Quote" => 0x34,
        "Backquote" => 0x35,
        "Comma" => 0x36,
        "Period" => 0x37,
        "Slash" => 0x38,
        "CapsLock" => 0x39,
        "F1" => 0x3A,
        "F2" => 0x3B,
        "F3" => 0x3C,
        "F4" => 0x3D,
        "F5" => 0x3E,
        "F6" => 0x3F,
        "F7" => 0x40,
        "F8" => 0x41,
        "F9" => 0x42,
        "F10" => 0x43,
        "F11" => 0x44,
        "F12" => 0x45,
        "PrintScreen" => 0x46,
        "ScrollLock" => 0x47,
        "Pause" => 0x48,
        "Insert" => 0x49,
        "Home" => 0x4A,
        "PageUp" => 0x4B,
        "Delete" => 0x4C,
        "End" => 0x4D,
        "PageDown" => 0x4E,
        "ArrowRight" => 0x4F,
        "ArrowLeft" => 0x50,
        "ArrowDown" => 0x51,
        "ArrowUp" => 0x52,
        "NumLock" => 0x53,
        "NumpadDivide" => 0x54,
        "NumpadMultiply" => 0x55,
        "NumpadSubtract" => 0x56,
        "NumpadAdd" => 0x57,
        "NumpadEnter" => 0x58,
        "Numpad1" => 0x59,
        "Numpad2" => 0x5A,
        "Numpad3" => 0x5B,
        "Numpad4" => 0x5C,
        "Numpad5" => 0x5D,
        "Numpad6" => 0x5E,
        "Numpad7" => 0x5F,
        "Numpad8" => 0x60,
        "Numpad9" => 0x61,
        "Numpad0" => 0x62,
        "NumpadDecimal" => 0x63,
        "IntlBackslash" => 0x64,
        "ContextMenu" => 0x65,
        "Power" => 0x66,
        "NumpadEqual" => 0x67,
        "F13" => 0x68,
        "F14" => 0x69,
        "F15" => 0x6A,
        "F16" => 0x6B,
        "F17" => 0x6C,
        "F18" => 0x6D,
        "F19" => 0x6E,
        "F20" => 0x6F,
        "F21" => 0x70,
        "F22" => 0x71,
        "F23" => 0x72,
        "F24" => 0x73,
        "AudioVolumeMute" => 0x7F,
        "AudioVolumeUp" => 0x80,
        "AudioVolumeDown" => 0x81,
        "NumpadComma" => 0x85,
        "IntlRo" => 0x87,
        "KanaMode" => 0x88,
        "IntlYen" => 0x89,
        "Convert" => 0x8A,
        "NonConvert" => 0x8B,
        "ControlLeft" => 0xE0,
        "ShiftLeft" => 0xE1,
        "AltLeft" => 0xE2,
        "MetaLeft" => 0xE3,
        "ControlRight" => 0xE4,
        "ShiftRight" => 0xE5,
        "AltRight" => 0xE6,
        "MetaRight" => 0xE7,
        // Older browsers' names for the same keys.
        "OSLeft" => 0xE3,
        "OSRight" => 0xE7,
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn keys_map_by_position() {
        assert_eq!(hid_usage("KeyA"), Some(0x04));
        assert_eq!(hid_usage("Digit0"), Some(0x27));
        assert_eq!(hid_usage("Enter"), Some(0x28));
        assert_eq!(hid_usage("IntlBackslash"), Some(0x64));
        assert_eq!(
            hid_usage("AltRight"),
            Some(0xE6),
            "AltGr is a key like any other"
        );
        assert_eq!(hid_usage("MetaLeft"), Some(0xE3));
        assert_eq!(hid_usage("Unidentified"), None);
        assert_eq!(hid_usage(""), None);
    }

    #[test]
    fn no_two_names_share_a_usage_unless_aliases() {
        let names = [
            "KeyA",
            "KeyB",
            "KeyC",
            "KeyD",
            "KeyE",
            "KeyF",
            "KeyG",
            "KeyH",
            "KeyI",
            "KeyJ",
            "KeyK",
            "KeyL",
            "KeyM",
            "KeyN",
            "KeyO",
            "KeyP",
            "KeyQ",
            "KeyR",
            "KeyS",
            "KeyT",
            "KeyU",
            "KeyV",
            "KeyW",
            "KeyX",
            "KeyY",
            "KeyZ",
            "Digit1",
            "Digit2",
            "Digit3",
            "Digit4",
            "Digit5",
            "Digit6",
            "Digit7",
            "Digit8",
            "Digit9",
            "Digit0",
            "Enter",
            "Escape",
            "Backspace",
            "Tab",
            "Space",
            "Minus",
            "Equal",
            "BracketLeft",
            "BracketRight",
            "Backslash",
            "Semicolon",
            "Quote",
            "Backquote",
            "Comma",
            "Period",
            "Slash",
            "CapsLock",
            "F1",
            "F2",
            "F3",
            "F4",
            "F5",
            "F6",
            "F7",
            "F8",
            "F9",
            "F10",
            "F11",
            "F12",
            "PrintScreen",
            "ScrollLock",
            "Pause",
            "Insert",
            "Home",
            "PageUp",
            "Delete",
            "End",
            "PageDown",
            "ArrowRight",
            "ArrowLeft",
            "ArrowDown",
            "ArrowUp",
            "NumLock",
            "NumpadDivide",
            "NumpadMultiply",
            "NumpadSubtract",
            "NumpadAdd",
            "NumpadEnter",
            "Numpad1",
            "Numpad2",
            "Numpad3",
            "Numpad4",
            "Numpad5",
            "Numpad6",
            "Numpad7",
            "Numpad8",
            "Numpad9",
            "Numpad0",
            "NumpadDecimal",
            "IntlBackslash",
            "ContextMenu",
            "Power",
            "NumpadEqual",
            "F13",
            "F14",
            "F15",
            "F16",
            "F17",
            "F18",
            "F19",
            "F20",
            "F21",
            "F22",
            "F23",
            "F24",
            "AudioVolumeMute",
            "AudioVolumeUp",
            "AudioVolumeDown",
            "NumpadComma",
            "IntlRo",
            "KanaMode",
            "IntlYen",
            "Convert",
            "NonConvert",
            "ControlLeft",
            "ShiftLeft",
            "AltLeft",
            "MetaLeft",
            "ControlRight",
            "ShiftRight",
            "AltRight",
            "MetaRight",
        ];
        let mut seen = std::collections::HashSet::new();
        for name in names {
            assert!(seen.insert(hid_usage(name).expect(name)), "{name}");
        }
    }
}
